### ISSUE TITLE
Podman Compatability

### ISSUE THREAD

**Issue by danemadsen** [princeton-nlp/SWE-agent#13]
Podman is a FOSS alternative to docker and should work out of the box.

**Comment by leehua03f3** [comment]
Not Podman but I had issue with Colima. `docker.from_env()` will fail because I think it's trying to get the default Docker's socket path. Setting DOCKER_HOST with `export DOCKER_HOST="unix://$HOME/.colima/default/docker.sock"` fixed it. It would be nice if this could be handled in the code along with Podman.

**Comment by xaptronic** [comment]
I symlinked `/opt/homebrew/bin/docker` to `/opt/homebrew/bin/podman` and it things seemed to work fine.

**Comment by ofirpress** [comment]
Looks like this can be closed. Thank you @xaptronic
