### ISSUE TITLE
Integration of Azure DevOps datapath

### ISSUE THREAD

**Issue by fleroyener** [princeton-nlp/SWE-agent#199]
### Describe the feature

Add an automatic datapath to use SWE-agent on Azure Devops repos. 

Steps to tests : 

1. Set `AZURE_DEVOPS_TOKEN` to Personal Access Token (PAT) in keys.cfg
`AZURE_DEVOPS_TOKEN=$AZURE_DEVOPS_PAT`
2. Run following command: 

```
python run.py --model_name azure:gpt4 \
  --data_path https://dev.azure.com/ORGANIZATION/PROJECT/_workitems/edit/WORK_ITEM_ID/ \
  --az_repo REPO_NAME \
  --config_file config/default_from_url.yaml
```

**REPO_NAME**: the repo name only (must be in same project) ex: 'SWE-agent'
**data_path**: Work item URL 

### Potential Solutions

I will create a PR

**Comment by klieret** [comment]
Hi @fleroyener . Thanks for the request and the PR, it looks like a lot of work went into this. I'm currently in the process of doing some refactoring to run on local repositories (see #43), so expect some merge conflicts in #200.

I also need to discuss with the team how general we want to be. 

Working with the local repository should fit all use cases (including yours, especially because yours won't support the `--open-pr` mechanic or similar yet). So I'm not yet sure if we can merge the PR or when.

**Comment by fleroyener** [comment]
Hi @klieret, understood. 
I'm waiting too for local repository feature, i agree this will fit all use case. 
I will watch this feature and if help is needed so i can contribute. 

I'm watching your PR right now 👍

**Comment by klieret** [comment]
(resolved with local repository feature -- we want to avoid increasing the maintenance burden of things like azure devops/gitlab etc., so we're currently not planning to add support for these directly -- though we hope to provide better APIs soon, so that people can build support themselves if needed)

**Comment by ofirpress** [comment]
sgtm, ty
